export const tagTypes = {
  auth: "Auth",
  otp: "Otp",
  customer: "Customer",
  csr: "CSR",
  admin: "Admin",
  common: "Common",
  settings: "Settings",
  category: "Category",
  products: "Products",
  user: "User",
  users: "Users",
  quote: "Quote",
  review: "Review",
  order: "Order",
  payment: "Payment",
  meta: "Meta",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.otp,
  tagTypes.customer,
  tagTypes.csr,
  tagTypes.admin,
  tagTypes.common,
  tagTypes.settings,
  tagTypes.category,
  tagTypes.products,
  tagTypes.user,
  tagTypes.users,
  tagTypes.quote,
  tagTypes.review,
  tagTypes.order,
  tagTypes.payment,
  tagTypes.meta,
];
